--------------------------------------------------------
--  DDL for Table ALLOWANCE
--------------------------------------------------------

  CREATE TABLE "HR"."ALLOWANCE" 
   (	"ID" NUMBER(*,0), 
	"OVERTIME" VARCHAR2(50 BYTE), 
	"MEDICAL" VARCHAR2(50 BYTE), 
	"BONUS" VARCHAR2(50 BYTE), 
	"OTHER" VARCHAR2(50 BYTE), 
	"EMP_ID" VARCHAR2(50 BYTE), 
	"SALARY" VARCHAR2(50 BYTE), 
	"RATE" VARCHAR2(20 BYTE), 
	"TOTAL_ALLOWANCE" VARCHAR2(100 BYTE), 
	"FIRSTNAME" VARCHAR2(100 BYTE), 
	"SURNAME" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEDUCTIONS
--------------------------------------------------------

  CREATE TABLE "HR"."DEDUCTIONS" 
   (	"ID" NUMBER, 
	"FIRSTNAME" VARCHAR2(100 BYTE), 
	"SURNAME" VARCHAR2(100 BYTE), 
	"SALARY" VARCHAR2(20 BYTE), 
	"DEDUCTION_AMOUNT" VARCHAR2(20 BYTE), 
	"DEDUCTION_REASON" VARCHAR2(100 BYTE), 
	"EMP_ID" VARCHAR2(20 BYTE), 
	"MADE_BY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUDITS
--------------------------------------------------------

  CREATE TABLE "HR"."AUDITS" 
   (	"AUDIT_ID" NUMBER(*,0), 
	"EMP_ID" NUMBER(*,0), 
	"A_DATE" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "HR"."USERS" 
   (	"ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(10 BYTE), 
	"PASSWORD" VARCHAR2(10 BYTE), 
	"DIVISION" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STAFF_INFORMATION
--------------------------------------------------------

  CREATE TABLE "HR"."STAFF_INFORMATION" 
   (	"ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"SURNAME" VARCHAR2(100 BYTE), 
	"DOB" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TELEPHONE" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"DEPARTMENT" VARCHAR2(100 BYTE), 
	"IMAGE" BLOB, 
	"GENDER" VARCHAR2(20 BYTE), 
	"SALARY" VARCHAR2(100 BYTE), 
	"ADDRESS2" VARCHAR2(100 BYTE), 
	"APARTMENT" VARCHAR2(100 BYTE), 
	"POST_CODE" VARCHAR2(100 BYTE), 
	"DESIGNATION" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(100 BYTE), 
	"JOB_TITLE" VARCHAR2(100 BYTE), 
	"DATE_HIRED" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index ALLOWANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."ALLOWANCE_PK" ON "HR"."ALLOWANCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEDUCTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."DEDUCTIONS_PK" ON "HR"."DEDUCTIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TABLE1_PK" ON "HR"."AUDITS" ("AUDIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006998
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C006998" ON "HR"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STAFF_INFORMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."STAFF_INFORMATION_PK" ON "HR"."STAFF_INFORMATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ALLOWANCE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."ALLOWANCE_TRIGGER" 
BEFORE INSERT ON allowance
FOR EACH ROW
BEGIN
:new.id := allowance_auto_incrmnt.nextval;
END;
/
ALTER TRIGGER "HR"."ALLOWANCE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEDUCTION_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."DEDUCTION_TRIGGER" 
BEFORE INSERT ON deductions
FOR EACH ROW
BEGIN
:new.id := deduction_auto_incrmnt.nextval;
END;
/
ALTER TRIGGER "HR"."DEDUCTION_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUDITS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."AUDITS_TRIGGER" 
BEFORE INSERT ON audits
FOR EACH ROW
BEGIN
:new.audit_id := audits_auto_incrmnt.nextval;
END;
/
ALTER TRIGGER "HR"."AUDITS_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table ALLOWANCE
--------------------------------------------------------

  ALTER TABLE "HR"."ALLOWANCE" ADD CONSTRAINT "ALLOWANCE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."ALLOWANCE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEDUCTIONS
--------------------------------------------------------

  ALTER TABLE "HR"."DEDUCTIONS" ADD CONSTRAINT "DEDUCTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."DEDUCTIONS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUDITS
--------------------------------------------------------

  ALTER TABLE "HR"."AUDITS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("AUDIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."AUDITS" MODIFY ("AUDIT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "HR"."USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STAFF_INFORMATION
--------------------------------------------------------

  ALTER TABLE "HR"."STAFF_INFORMATION" ADD CONSTRAINT "STAFF_INFORMATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."STAFF_INFORMATION" MODIFY ("ID" NOT NULL ENABLE);
