CREATE TABLE ALLOWANCE 
(
  ID INTEGER NOT NULL 
, OVERTIME VARCHAR(50) 
, MEDICAL VARCHAR(50) 
, BONUS VARCHAR(50) 
, OTHER VARCHAR(50) 
, EMP_ID VARCHAR(50) 
, SALARY VARCHAR(50) 
, RATE VARCHAR(20) 
, TOTAL_ALLOWANCE VARCHAR(100) 
, FIRSTNAME VARCHAR(100) 
, SURNAME VARCHAR(100) 
, CREATED_BY VARCHAR(100) 
, CONSTRAINT ALLOWANCE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);
